name: Update Packages in Port

on:
  push:
    branches:
      - "main"
    paths:
      - "package-lock.json"
  workflow_dispatch:
    
    


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run scanner script
        env:
          MICROSERVICE_ID: "sample-microservice"
          CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
        run: python scripts/scan-package-lock.py 